"""autogenerated by genmsg_py from Raw.msg. Do not edit."""
import roslib.message
import struct

import std_msgs.msg

class Raw(roslib.message.Message):
  _md5sum = "abda63674ce89e542bda766f5d8939f7"
  _type = "sixense/Raw"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
int16[6] pos
int16[8] quat
uint8[2] buttons
int16[6] analog

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','pos','quat','buttons','analog']
  _slot_types = ['Header','int16[6]','int16[8]','uint8[2]','int16[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       header,pos,quat,buttons,analog
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Raw, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.pos is None:
        self.pos = [0,0,0,0,0,0]
      if self.quat is None:
        self.quat = [0,0,0,0,0,0,0,0]
      if self.buttons is None:
        self.buttons = chr(0)*2
      if self.analog is None:
        self.analog = [0,0,0,0,0,0]
    else:
      self.header = std_msgs.msg._Header.Header()
      self.pos = [0,0,0,0,0,0]
      self.quat = [0,0,0,0,0,0,0,0]
      self.buttons = chr(0)*2
      self.analog = [0,0,0,0,0,0]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_6h.pack(*self.pos))
      buff.write(_struct_8h.pack(*self.quat))
      _x = self.buttons
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_2B.pack(*_x))
      else:
        buff.write(_struct_2s.pack(_x))
      buff.write(_struct_6h.pack(*self.analog))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      start = end
      end += 12
      self.pos = _struct_6h.unpack(str[start:end])
      start = end
      end += 16
      self.quat = _struct_8h.unpack(str[start:end])
      start = end
      end += 2
      self.buttons = str[start:end]
      start = end
      end += 12
      self.analog = _struct_6h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(self.pos.tostring())
      buff.write(self.quat.tostring())
      _x = self.buttons
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_2B.pack(*_x))
      else:
        buff.write(_struct_2s.pack(_x))
      buff.write(self.analog.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      start = end
      end += 12
      self.pos = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=6)
      start = end
      end += 16
      self.quat = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=8)
      start = end
      end += 2
      self.buttons = str[start:end]
      start = end
      end += 12
      self.analog = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=6)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6h = struct.Struct("<6h")
_struct_3I = struct.Struct("<3I")
_struct_8h = struct.Struct("<8h")
_struct_2B = struct.Struct("<2B")
_struct_2s = struct.Struct("<2s")
